### ISSUE TITLE
Verify Asteroids Revenge on Flathub

### ISSUE THREAD

**Issue by overwatcheddude** [flathub/io.github.mlm.asteroids_revenge#5]
You can find the steps here:
https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by mlm-games** [comment]
Well i will have to rename the app to io.github.mlm-games.asteroids_revenge as my current name cant be used for verifying as the name was taken by someone else.

**Comment by mlm-games** [comment]
The app-id has been renamed and it is now verified.
